### PR TITLE
My less-than-cool new code feature is ready.

### PR DESCRIPTION
**Pull request by KineticTheory**
Create some dummy changes to walk through the github workflow and create some documentation.

### CODE REVIEW

**Comment by nukularrr** [comment]
I'm not authorized to merge the pull request, but it looks like this is working.

**Comment by junghans** [comment]
If you merge the recent `develop` branch back into the `cool_new_feature` branch and push again, it should now trigger testing.

**Comment by junghans** [comment]
Oh yeah, and you will get a codecov diff with every pull request as well.

**Comment by jhchang-lanl** [comment]
Looks ok to me. Not sure it's a cool feature though.

**Comment by lowrie** [comment]
Definitely a highlight.

**Comment by junghans** [comment]
Yeah, 72.92% code coverage is a definitely outstanding!

**Comment by KineticTheory** [comment]
@junghans The codecov-io is something I need to work on.  Our CDash page shows:

| Machine | Build Name | Coverage |
| --- | --- | --- |
| ccscs7 | Linux64_gcc_Debug_Cov | 97.41%	|

**Comment by junghans** [comment]
I guess this stems for the fact that I had to disable a couple of tests on travis ci, see:
https://github.com/losalamos/Draco/blob/develop/.travis.yml#L43

**Comment by KineticTheory** [comment]
That and we use a BullseyeCoverage with some filters instead of gcov.

**Pull request merged**
