### PR TITLE
Set communication size when inverting map.

### PR DESCRIPTION
**Pull request by lowrie**
* Refs #103 

* [Pre-Merge Code Review](https://github.com/losalamos/Draco/wiki/Style-Guide)
  * [ ] Travis CI checks pass
  * [x] Code coverage does not decrease
  * [x] [Valgrind test passes](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Toss2 checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [x] [Trinitite checks pass](https://rtt.lanl.gov/CDash/index.php?project=Draco)
  * [ ] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by lowrie** [comment]
Travis appears to be using MPI 1.6, which takes the first arg of MPI_Put as "void *", rather than "const void *".  Can we use a later version of MPI for this, or do we need to keep supporting old MPI versions?

**Comment by KineticTheory** [comment]
@lowrie I can update travis to use a newer MPI, but I'm not sure if I will get to it today.  I will also update the build system to fail if MPI is too old.

**Comment by lowrie** [comment]
@KineticTheory no rush on newer MPI

**Comment by KineticTheory** [comment]
#111 will change the regression system to use openmpi-1.10.3.

**Comment by KineticTheory** [comment]
@lowrie To do:

* [ ] Address merge conflict, but don't push until #111 is merged.
* [ ] If #111 is merged, pushed the above change will trigger a new Travis build that should work since Travis will know about OpenMPI-1.10.3.

**Comment by KineticTheory** [comment]
@lowrie @alexrlongne I don't think the CI will start until the merge conflict is resolved.  Alex and I can do this for you.

**Comment by alexrlongne** [comment]
Replaced by #113.

**Pull request closed without merging**
