### PR TITLE
Cleanup links used in published autodoc (rtt.lanl.gov/autodoc).

### PR DESCRIPTION
**Pull request by KineticTheory**
* [Pre-Merge Code Review](https://github.com/losalamos/Draco/wiki/Style-Guide)
  * [ ] Travis CI checks pass
  * [ ] Code reviewed/approved, sufficient DbC checks, testing, documentation

### CODE REVIEW

**Comment by KineticTheory** [comment]
@RyanWollaeger Can you review and merge this PR?  There are no changes to source code. So, no need to run any additional tests.  If you want to see what it does, you can checkout the PR manually and run `module load graphviz; make autodoc` from ccscs7.  Run `firefox $install_dir/index.html` to view the result.

**Comment by RyanWollaeger** [comment]
@KineticTheory I will certainly review this PR.  Howerver, the "Merge pull request" button indicates I am not authorized to merge pull requests (apologies - I meant to mention this sooner).

**Comment by KineticTheory** [comment]
@RyanWollaeger Permissions fixed.

**Comment by RyanWollaeger** [comment]
Tested on ccscs7 just to view the result.

**Pull request merged**
